### PR TITLE
Support Vue

### LINKED ISSUE #46: Support Vue
Is this even a thing in Vue?

```javascript
import Vue from 'vue'
import { css } from './index'

export default function (tag, cls, vars = [], content) {
  return Vue.component('styled', {
    props: ['class'],
    template: `<${tag} v-bind:class="[{{class}}, ${css(
      cls,
      vars.map(v => (v && typeof v === 'function' ? v(props) : v)),
      content
    )}]"><slot></slot></p>`
  })
}
```

Suggested solution:
Learn Vue

### PR DESCRIPTION
**Pull request by mitchellhamilton**
**What**:

Support Vue

**Why**:

#46 

**How**:

**Checklist**:

- [x] Documentation
- [x] Tests
- [x] Code complete

Closes #46

### CODE REVIEW

**Comment by tkh44** [comment]
@mitchellhamilton I added a "merge me" label from now on I'll hold off until that is on there. I'll also add this to the PR template.

**Comment by mitchellhamilton** [comment]
@tkh44 Are non-collaborators allowed to add labels?

**Comment by tkh44** [comment]
Whoops! I guess we'll just use it for our purposes then.

**Comment by Aaron-Pool** [comment]
I'm confused. It looks like this got merged, but I can't find it anywhere?

**Comment by Andarist** [comment]
@Aaron-Pool this was added long time ago (when the latest emotion was v4), but possibly due to lack of time resources on the emotion team this got discontinued

**Comment by Aaron-Pool** [comment]
So, our team, was concerned with the support of things like the babel-plugin with vue-emotion. It works pretty well, but we're afraid the different `styled` implementation may present issues.

Is that not the case?

**Comment by Andarist** [comment]
Not entirely sure what do u mean - but it would be better to discuss this in a new issue.

**Comment by Aaron-Pool** [comment]
Right! 👍

**Pull request merged**
