### PR TITLE
chore: fix install README babel instructions

### PR DESCRIPTION
**Pull request by probablyup**

### CODE REVIEW

**Comment by probablyup** [comment]
Ah. Is that the recommended way to use emotion going forward? It was kind
of nice having things coalesced in the main package.

**Comment by mitchellhamilton** [comment]
@probablyup It is. Currently, everything is aliased so all the old imports still work but we'll likely remove them in the next major version.

**Comment by probablyup** [comment]
@mitchellhamilton updated

**Comment by probablyup** [comment]
@mitchellhamilton Why'd you add `emotion` as well? It's already a hard dependency for both of those packages.

**Comment by mitchellhamilton** [comment]
@probablyup Some people don't want react-emotion.

**Comment by probablyup** [comment]
Perhaps, but I wouldn't want both of those installed at the same time. That'd be confusing.

**Pull request merged**
