### PR TITLE
Upgrade bundlesize to 0.13.2

### PR DESCRIPTION
**Pull request by siddharthkp**
**What**:
Upgrading bundlesize to 0.13.2

**Why**:
This update adds a better UI for multiple files: https://github.com/siddharthkp/bundlesize/issues/55#issuecomment-315567994

**How**:
Update version in `package.json`

**Checklist**:
- [ ] Documentation: NA
- [ ] Tests: NA
- [ ] Code complete: NA

### CODE REVIEW

**Comment by siddharthkp** [comment]
@mitchellhamilton bundlesize only works on travis-ci/push though 😢 

Should I make that configuration? 🤔

**Comment by mitchellhamilton** [comment]
I think it only works on push because the environment variable is secret so it's not exposed on forks. I think you could do this without having to have the API key be public with [this](https://docs.travis-ci.com/user/jwt) or something else, like what codecov does how it doesn't require an environment variable at all(I'm not sure how that works though).

**Comment by siddharthkp** [comment]
That's super helpful! I'll check what codecov does

**Comment by tkh44** [comment]
Thank you @siddharthkp

**Pull request merged**
