### PR TITLE
Use spread over Object.assign

### PR DESCRIPTION
**Pull request by bogas04**
**What**: Object.assign is being replaced by Object spread syntax.

**Why**: Object spread doesn't require you to also include polyfill for Object.assign, hence it's better for users trying it out on older browsers.

**Checklist**:

- [ ] Documentation
- [ ] Tests
- [ ] Code complete

### CODE REVIEW

**Comment by thangngoc89** [comment]
>  Object spread doesn't require you to also include polyfill for Object.assign, hence it's better for users trying it out on older browsers

Actually, babel includes Object.assign polyfill for object spread.

**Comment by bogas04** [comment]
@thangngoc89 it includes it for spread, but if you directly use Object.assign, then the user library will need to add polyfill.

**Comment by bogas04** [comment]
Thank you so much for accepting the PR ! I feel I didn't quite explain myself well. Either way, kudos to Emotion for being awesome !

**Comment by thangngoc89** [comment]
Yeah. I didn't think about manually providing Object.assign polyfill

**Comment by bogas04** [comment]
@thangngoc89 Sorry for the rush, but when can I expect this patch to get released to npm ? Thanks!

**Comment by thangngoc89** [comment]
@bogas04 No idea. Ask @tkh44 . Current he's focusing on shaping version 7.0 which is a major rewrote of emotion core

**Pull request merged**
