### PR TITLE
Theming

### LINKED ISSUE #17: Theme support
Hello,

do you intend to support theming with emotion ? ✨

### LINKED ISSUE #35: theming support

### PR DESCRIPTION
**Pull request by tkh44**
**What**:
Add support for themes

**Why**:
They are nice to work with

**How**:
Adding ThemeProvider component and withTheme hoc. 

**Checklist**:

- [ ] Documentation
- [ ] Tests
- [ ] Code complete

closes #17 
closes #35

### CODE REVIEW

**Comment by k15a** [comment]
Hey, you may want to checkout https://www.npmjs.com/package/theming which is a unified theming solution for CSSinJS solutions. We at styled-components want to eventually swap to theming as well.

**Comment by tkh44** [comment]
For some reason theming is huge.
```
Approximate weight of theming:
  Uncompressed: 170 kB
  Minified (uglify): 41.8 kB
  Minified and gzipped (level: default): 12.4 kB
```

**Comment by tkh44** [comment]
It looks like they are bundling prop-types in their bundle.

I think it would be a good idea to use that if we can. I don't want to maintain a theming solution.

**Comment by k15a** [comment]
Where did you get this stats from? I think it's 10kb Uncompressed.

**Comment by tkh44** [comment]
the tool `weigh` gets the entire cost of using a library. The cost of using theming includes prop-types. Since we are already using prop-types this doesn't matter.

I'm going to put npmjs.com/package/theming in tonight

**Pull request closed without merging**
