### PR TITLE
Optimize hash.js

### PR DESCRIPTION
**Pull request by thangngoc89**
**What**:

Optimize hash.js

**Why**:

Speed.

**How**:
Since anything in `for(...)` will be executed in each loop, extract and cache them outside the loop can improve perfomance alot.

**Checklist**:

- [ ] Documentation
- [x] Tests
- [ ] Code complete

---

Update: Gonna use `@arr/forEach` to avoid duplicate

### CODE REVIEW

**Comment by thangngoc89** [comment]
@tkh44 At first, I want to use `@arr/forEach` to save some bytes but with the cost of invoking a function.

I have [some benchmark here](https://esbench.com/bench/59653b8499634800a03489b4)

What is you opinion here? 

image

**Comment by tkh44** [comment]
@thangngoc89 I don't think that's enough of a speed difference to justify the reduction in readability.

**Comment by k15a** [comment]
AFAIK the engines do this kind of optimization automatically.

**Comment by lukeed** [comment]
It wasn't losing because of the function call, but rather the extra set of spread arguments. Removing those, and casting all use cases to ES5 produces these results:

screen shot 2017-07-11 at 2 53 47 pm

That said, it's not consistent. The three are close enough that any one of them can "win" the results chart. In fact, it's pretty even.

**Comment by tkh44** [comment]
I would rather just use @arr/forEach because we use that everywhere else. What do you think @thangngoc89? Fair compromise?

**Comment by lukeed** [comment]
@tkh44 Looks like you forgot a word somewhere 👻 Use what?

**Comment by tkh44** [comment]
Whoops! It looks like github doesn't like the namespace `@arr/forEach` and just deleted it.

**Comment by lukeed** [comment]
Gotcha. IMO, I would remove the spreads & do

```js
var objs = [].slice.call(arguments)
```

It's not _ideal_, but it's a whole lot better than the helper Babel will give you.

**Comment by thangngoc89** [comment]
@lukeed I don't understand this point:

> but rather the extra set of spread arguments

All functions in the bench are the same, only different in the iterator code.

@tkh44 yeah. I also prefer using forEach to save bytes. Bytes matter :p 

@k15a my benchmark result was executed on Chrome.

**Pull request closed without merging**
